# Generated by Django 3.0.8 on 2020-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairprofile',
            name='naturally_dried_looks',
        ),
        migrations.AddField(
            model_name='hairprofile',
            name='texture',
            field=models.CharField(choices=[('1', 'Smooth/Straight'), ('2', 'Wavy'), ('3', 'Curly')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='appliances',
            field=models.CharField(choices=[('1', 'Hair Dryer'), ('2', 'Hair Straightner'), ('3', 'Curling Iron'), ('4', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='chemical_treatment',
            field=models.CharField(choices=[('1', 'Short'), ('2', 'Yes, Straightening or Waving'), ('3', 'Yes, Keratin or Cysteine treatment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='colored',
            field=models.CharField(choices=[('1', 'Highlighted'), ('2', 'Permanent'), ('3', 'Semi-Permanent'), ('4', 'Bleached')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='dyed_choices',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='style',
            field=models.CharField(choices=[('1', 'Hair Oil'), ('2', 'Gel or Paste'), ('3', 'Dry Shampoo'), ('4', 'Hair Spray'), ('5', 'Mousse'), ('6', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='sunlight_exposure',
            field=models.CharField(choices=[('1', '1 hour'), ('2', '1-3 hours'), ('3', 'More than 3 hours')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='volume',
            field=models.CharField(choices=[('1', 'Very low volume'), ('2', 'Moderate volume'), ('3', 'Voluminous')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='water_hardness',
            field=models.CharField(choices=[('1', 'Soft'), ('2', 'Hard'), ('3', 'I do not know')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='dandruff',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Little bit'), ('3', 'A lot')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='hair_loss',
            field=models.CharField(choices=[('1', 'A few hair strands'), ('2', 'A dozen hair strands'), ('3', 'More than a dozen hair strands')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='length',
            field=models.CharField(choices=[('1', 'Short'), ('2', 'Medium(upto shoulders)'), ('3', 'Long (longer than shoulders)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='scalp',
            field=models.CharField(choices=[('1', 'Not sensitive'), ('2', 'A little bit itchy'), ('3', 'Itchy and Painful')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='state',
            field=models.CharField(choices=[('1', 'Dry'), ('2', 'Normal'), ('3', 'Oily'), ('4', 'Oily with dry ends')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='thickness',
            field=models.CharField(choices=[('1', 'Thin/Finer than Thread'), ('2', 'Medium/Same as Thread'), ('3', 'Coarse/Thicker than thread')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='volume',
            field=models.CharField(choices=[('1', 'Very low volume'), ('2', 'Moderate volume'), ('3', 'Voluminous')], max_length=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='hair_goals',
            field=models.CharField(choices=[('1', 'Shine'), ('2', 'Smoothness'), ('3', 'Lengthen'), ('4', 'Volume'), ('5', 'Thickness'), ('6', 'Strengthen'), ('7', 'Fix split ends'), ('8', 'Anti-Dryness'), ('9', 'Oil COntrol'), ('10', 'Anti-Frizz'), ('11', 'Damage Repair'), ('12', 'Anti-dandruff'), ('13', 'Color Protection'), ('14', 'Thermal Protection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='product_color',
            field=models.CharField(choices=[('1', 'Peach (with Apricot)'), ('2', 'Pink (with Strawberry'), ('3', 'Blue (with Blueberry'), ('4', 'Green (with Avocado)')], max_length=30),
        ),
    ]
