# Generated by Django 3.0.8 on 2020-07-24 10:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20200724_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfactors',
            name='appliances',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Hair Dryer'), ('2', 'Hair Straightner'), ('3', 'Curling Iron'), ('4', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Hair Oil'), ('2', 'Gel or Paste'), ('3', 'Dry Shampoo'), ('4', 'Hair Spray'), ('5', 'Mousse'), ('6', 'None')], max_length=1),
        ),
    ]
