# Generated by Django 3.0.8 on 2020-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20200724_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfactors',
            name='colored',
            field=models.CharField(blank=True, choices=[('1', 'Highlighted'), ('2', 'Permanent'), ('3', 'Semi-Permanent'), ('4', 'Bleached')], max_length=1, null=True),
        ),
    ]
