# Generated by Django 3.0.8 on 2020-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20200731_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfactors',
            name='appliances',
            field=models.CharField(choices=[('1', 'Hair Dryer'), ('2', 'Hair Straightner'), ('3', 'Curling Iron'), ('4', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='externalfactors',
            name='style',
            field=models.CharField(choices=[('1', 'Hair Oil'), ('2', 'Gel or Paste'), ('3', 'Dry Shampoo'), ('4', 'Hair Spray'), ('5', 'Mousse'), ('6', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='hair_goals',
            field=models.CharField(choices=[('1', 'Shine'), ('2', 'Smoothness'), ('3', 'Lengthen'), ('4', 'Volume'), ('5', 'Thickness'), ('6', 'Strengthen'), ('7', 'Fix split ends'), ('8', 'Anti-Dryness'), ('9', 'Oil COntrol'), ('10', 'Anti-Frizz'), ('11', 'Damage Repair'), ('12', 'Anti-dandruff'), ('13', 'Color Protection'), ('14', 'Thermal Protection')], max_length=2),
        ),
    ]
